class RevGuess < ActiveRecord::Base
  extend _ActiveRecord_Relation_ClassMethods[RevGuess, ActiveRecord_Relation, Integer]

  attr_accessor id(): Integer
  def id_changed?: () -> bool
  def id_change: () -> [ Integer?, Integer? ]
  def id_will_change!: () -> void
  def id_was: () -> Integer?
  def id_previously_changed?: () -> bool
  def id_previous_change: () -> Array[Integer?]?
  def id_previously_was: () -> Integer?
  def id_before_last_save: () -> Integer?
  def id_change_to_be_saved: () -> Array[Integer?]?
  def id_in_database: () -> Integer?
  def saved_change_to_id: () -> Array[Integer?]?
  def saved_change_to_id?: () -> bool
  def will_save_change_to_id?: () -> bool
  def restore_id!: () -> void
  def clear_id_change: () -> void

  attr_accessor match_id(): Integer?
  def match_id_changed?: () -> bool
  def match_id_change: () -> [ Integer?, Integer? ]
  def match_id_will_change!: () -> void
  def match_id_was: () -> Integer?
  def match_id_previously_changed?: () -> bool
  def match_id_previous_change: () -> Array[Integer?]?
  def match_id_previously_was: () -> Integer?
  def match_id_before_last_save: () -> Integer?
  def match_id_change_to_be_saved: () -> Array[Integer?]?
  def match_id_in_database: () -> Integer?
  def saved_change_to_match_id: () -> Array[Integer?]?
  def saved_change_to_match_id?: () -> bool
  def will_save_change_to_match_id?: () -> bool
  def restore_match_id!: () -> void
  def clear_match_id_change: () -> void

  attr_accessor user_id(): Integer?
  def user_id_changed?: () -> bool
  def user_id_change: () -> [ Integer?, Integer? ]
  def user_id_will_change!: () -> void
  def user_id_was: () -> Integer?
  def user_id_previously_changed?: () -> bool
  def user_id_previous_change: () -> Array[Integer?]?
  def user_id_previously_was: () -> Integer?
  def user_id_before_last_save: () -> Integer?
  def user_id_change_to_be_saved: () -> Array[Integer?]?
  def user_id_in_database: () -> Integer?
  def saved_change_to_user_id: () -> Array[Integer?]?
  def saved_change_to_user_id?: () -> bool
  def will_save_change_to_user_id?: () -> bool
  def restore_user_id!: () -> void
  def clear_user_id_change: () -> void

  attr_accessor home_goals(): Integer?
  def home_goals_changed?: () -> bool
  def home_goals_change: () -> [ Integer?, Integer? ]
  def home_goals_will_change!: () -> void
  def home_goals_was: () -> Integer?
  def home_goals_previously_changed?: () -> bool
  def home_goals_previous_change: () -> Array[Integer?]?
  def home_goals_previously_was: () -> Integer?
  def home_goals_before_last_save: () -> Integer?
  def home_goals_change_to_be_saved: () -> Array[Integer?]?
  def home_goals_in_database: () -> Integer?
  def saved_change_to_home_goals: () -> Array[Integer?]?
  def saved_change_to_home_goals?: () -> bool
  def will_save_change_to_home_goals?: () -> bool
  def restore_home_goals!: () -> void
  def clear_home_goals_change: () -> void

  attr_accessor away_goals(): Integer?
  def away_goals_changed?: () -> bool
  def away_goals_change: () -> [ Integer?, Integer? ]
  def away_goals_will_change!: () -> void
  def away_goals_was: () -> Integer?
  def away_goals_previously_changed?: () -> bool
  def away_goals_previous_change: () -> Array[Integer?]?
  def away_goals_previously_was: () -> Integer?
  def away_goals_before_last_save: () -> Integer?
  def away_goals_change_to_be_saved: () -> Array[Integer?]?
  def away_goals_in_database: () -> Integer?
  def saved_change_to_away_goals: () -> Array[Integer?]?
  def saved_change_to_away_goals?: () -> bool
  def will_save_change_to_away_goals?: () -> bool
  def restore_away_goals!: () -> void
  def clear_away_goals_change: () -> void

  attr_accessor comment(): String?
  def comment_changed?: () -> bool
  def comment_change: () -> [ String?, String? ]
  def comment_will_change!: () -> void
  def comment_was: () -> String?
  def comment_previously_changed?: () -> bool
  def comment_previous_change: () -> Array[String?]?
  def comment_previously_was: () -> String?
  def comment_before_last_save: () -> String?
  def comment_change_to_be_saved: () -> Array[String?]?
  def comment_in_database: () -> String?
  def saved_change_to_comment: () -> Array[String?]?
  def saved_change_to_comment?: () -> bool
  def will_save_change_to_comment?: () -> bool
  def restore_comment!: () -> void
  def clear_comment_change: () -> void

  attr_accessor created_at(): ActiveSupport::TimeWithZone?
  def created_at_changed?: () -> bool
  def created_at_change: () -> [ ActiveSupport::TimeWithZone?, ActiveSupport::TimeWithZone? ]
  def created_at_will_change!: () -> void
  def created_at_was: () -> ActiveSupport::TimeWithZone?
  def created_at_previously_changed?: () -> bool
  def created_at_previous_change: () -> Array[ActiveSupport::TimeWithZone?]?
  def created_at_previously_was: () -> ActiveSupport::TimeWithZone?
  def created_at_before_last_save: () -> ActiveSupport::TimeWithZone?
  def created_at_change_to_be_saved: () -> Array[ActiveSupport::TimeWithZone?]?
  def created_at_in_database: () -> ActiveSupport::TimeWithZone?
  def saved_change_to_created_at: () -> Array[ActiveSupport::TimeWithZone?]?
  def saved_change_to_created_at?: () -> bool
  def will_save_change_to_created_at?: () -> bool
  def restore_created_at!: () -> void
  def clear_created_at_change: () -> void

  attr_accessor updated_at(): ActiveSupport::TimeWithZone?
  def updated_at_changed?: () -> bool
  def updated_at_change: () -> [ ActiveSupport::TimeWithZone?, ActiveSupport::TimeWithZone? ]
  def updated_at_will_change!: () -> void
  def updated_at_was: () -> ActiveSupport::TimeWithZone?
  def updated_at_previously_changed?: () -> bool
  def updated_at_previous_change: () -> Array[ActiveSupport::TimeWithZone?]?
  def updated_at_previously_was: () -> ActiveSupport::TimeWithZone?
  def updated_at_before_last_save: () -> ActiveSupport::TimeWithZone?
  def updated_at_change_to_be_saved: () -> Array[ActiveSupport::TimeWithZone?]?
  def updated_at_in_database: () -> ActiveSupport::TimeWithZone?
  def saved_change_to_updated_at: () -> Array[ActiveSupport::TimeWithZone?]?
  def saved_change_to_updated_at?: () -> bool
  def will_save_change_to_updated_at?: () -> bool
  def restore_updated_at!: () -> void
  def clear_updated_at_change: () -> void

  attr_accessor score(): Integer?
  def score_changed?: () -> bool
  def score_change: () -> [ Integer?, Integer? ]
  def score_will_change!: () -> void
  def score_was: () -> Integer?
  def score_previously_changed?: () -> bool
  def score_previous_change: () -> Array[Integer?]?
  def score_previously_was: () -> Integer?
  def score_before_last_save: () -> Integer?
  def score_change_to_be_saved: () -> Array[Integer?]?
  def score_in_database: () -> Integer?
  def saved_change_to_score: () -> Array[Integer?]?
  def saved_change_to_score?: () -> bool
  def will_save_change_to_score?: () -> bool
  def restore_score!: () -> void
  def clear_score_change: () -> void

  def match: () -> Match
  def match=: (Match?) -> Match?
  def reload_match: () -> Match?
  def build_match: (untyped) -> Match
  def create_match: (untyped) -> Match
  def create_match!: (untyped) -> Match
  def user: () -> User
  def user=: (User?) -> User?
  def reload_user: () -> User?
  def build_user: (untyped) -> User
  def create_user: (untyped) -> User
  def create_user!: (untyped) -> User

  module GeneratedRelationMethods
  end

  class ActiveRecord_Relation < ActiveRecord::Relation
    include GeneratedRelationMethods
    include _ActiveRecord_Relation[RevGuess, Integer]
    include Enumerable[RevGuess]
  end

  class ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
    include GeneratedRelationMethods
    include _ActiveRecord_Relation[RevGuess, Integer]
  end
end
