#!/bin/bash -e

cd "$(dirname "$0")/.."

args=( "$@" )

if [ "$#" -lt 1 ]; then args=( "./..." ); fi

script/setup

docker-compose run --service-ports web go test -covermode atomic -coverprofile cover.out -race "${args[@]}"
