---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: false
  csslint:
    enabled: false
  coffeelint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: false
  scss-lint:
    enabled: false
ratings:
  paths:
  - "**.erb"
  - "**.rb"
  - "**.haml"
  - "**.css"
  - "**.scss"
  - "**.coffee"
  - "**.js"
  - "**.es6"
  - "**.jsx"
  - "**.module"
