# rubocop configuration file
#

AllCops:
  Exclude:
    - "vendor/**/*"
    - "db/schema.rb"
    - "spec/fixtures/**/*"
    - "db/migrate/*"
  UseCache: false
  DefaultFormatter: progress
  DisplayStyleGuide: true
  DisplayCopNames: false
  TargetRubyVersion: 2.3

Rails:
  Enabled: true

Lint/EndAlignment:
  AlignWith: variable
  Enabled: true

Metrics/LineLength:
  Max: 150
  Enabled: false

Performance/StringReplacement:
  Enabled: false

Style/AlignParameters:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: semantic
  Enabled: true
  Exclude:
    - spec/**/*

Style/ClosingParenthesisIndentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/CollectionMethods:
  Enabled: true
  PreferredMethods:
    collect: map
    collect!: map!
    inject: reduce
    detect: find

Style/Documentation:
  Enabled: false

Style/DotPosition:
  Enabled: true
  EnforcedStyle: leading

Style/EmptyLinesAroundBlockBody:
  Exclude:
    - spec/**/*

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IndentHash:
  Enabled: true
  EnforcedStyle: consistent

Style/MultilineArrayBraceLayout:
  Enabled: true

Style/MultilineHashBraceLayout:
  Enabled: true

Style/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

Style/MultilineOperationIndentation:
  EnforcedStyle: indented
  Enabled: true

Style/PredicateName:
  # Predicate name prefixes.
  NamePrefix:
    - is_
    - has_
    - have_
  # Predicate name prefixes that should be removed.
  NamePrefixBlacklist:
    - is_
    - has_
    - have_
  # Predicate names which, despite having a blacklisted prefix, or no ?,
  # should still be accepted
  NameWhitelist:
    - is_a?
  Exclude:
    - spec/**/*

Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true
  Enabled: true

Style/Send:
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#prefer-public-send'
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

Style/SymbolArray:
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#percent-i'
  Enabled: true

Style/VariableName:
  EnforcedStyle: snake_case
  Enabled: true

Rails/HttpPositionalArguments:
  Enabled: false
