version: "3.7"
services:
  server:
    build:
      context: .
      dockerfile: Dev.dockerfile
    command:
      - bin/dev
    depends_on:
      - db
      - start_db
    environment:
      APP_ENV: "${APP_ENV:-development}"
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/mr_member_portal_${DBENV:-development}"
      LOCAL_HOST_AND_PORT: 'localhost:5991'
      MAILER_HOST: 'host.docker.internal'
      MAILER_PORT: '1025'
      RAILS_ENV: "${RAILS_ENV:-development}"
      PORT: 8080
    ports:
      - '5991:8080'
      - '5999:5999'
    tty: true
    volumes:
      - .:/usr/src/member-portal
      - /usr/src/member-portal/node_modules
  db:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: "mr_member_portal_${DBENV:-development}"
    image: postgres:11.17-alpine
    ports:
      - '5992:5432'
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
  start_db:
    image: dadarek/wait-for-dependencies
    depends_on:
      - db
    environment:
      TIMEOUT_LENGTH: 30
    command: db:5432
volumes:
  pgdata:
