// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type Conference string

const (
	ConferenceEastern Conference = "Eastern"
	ConferenceWestern Conference = "Western"
)

var AllConference = []Conference{
	ConferenceEastern,
	ConferenceWestern,
}

func (e Conference) IsValid() bool {
	switch e {
	case ConferenceEastern, ConferenceWestern:
		return true
	}
	return false
}

func (e Conference) String() string {
	return string(e)
}

func (e *Conference) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Conference(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Conference", str)
	}
	return nil
}

func (e Conference) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type MatchStatus string

const (
	MatchStatusUpcoming  MatchStatus = "Upcoming"
	MatchStatusDelayed   MatchStatus = "Delayed"
	MatchStatusPostponed MatchStatus = "Postponed"
	MatchStatusStarted   MatchStatus = "Started"
	MatchStatusFinished  MatchStatus = "Finished"
)

var AllMatchStatus = []MatchStatus{
	MatchStatusUpcoming,
	MatchStatusDelayed,
	MatchStatusPostponed,
	MatchStatusStarted,
	MatchStatusFinished,
}

func (e MatchStatus) IsValid() bool {
	switch e {
	case MatchStatusUpcoming, MatchStatusDelayed, MatchStatusPostponed, MatchStatusStarted, MatchStatusFinished:
		return true
	}
	return false
}

func (e MatchStatus) String() string {
	return string(e)
}

func (e *MatchStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MatchStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MatchStatus", str)
	}
	return nil
}

func (e MatchStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type MembershipType string

const (
	MembershipTypeIndividual MembershipType = "Individual"
	MembershipTypeFamily     MembershipType = "Family"
)

var AllMembershipType = []MembershipType{
	MembershipTypeIndividual,
	MembershipTypeFamily,
}

func (e MembershipType) IsValid() bool {
	switch e {
	case MembershipTypeIndividual, MembershipTypeFamily:
		return true
	}
	return false
}

func (e MembershipType) String() string {
	return string(e)
}

func (e *MembershipType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MembershipType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MembershipType", str)
	}
	return nil
}

func (e MembershipType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type Position string

const (
	PositionGoalkeeper Position = "Goalkeeper"
	PositionDefender   Position = "Defender"
	PositionMidfielder Position = "Midfielder"
	PositionAttacker   Position = "Attacker"
)

var AllPosition = []Position{
	PositionGoalkeeper,
	PositionDefender,
	PositionMidfielder,
	PositionAttacker,
}

func (e Position) IsValid() bool {
	switch e {
	case PositionGoalkeeper, PositionDefender, PositionMidfielder, PositionAttacker:
		return true
	}
	return false
}

func (e Position) String() string {
	return string(e)
}

func (e *Position) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Position(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Position", str)
	}
	return nil
}

func (e Position) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type Role string

const (
	RoleExecutiveBoard Role = "ExecutiveBoard"
	RoleAtLargeBoard   Role = "AtLargeBoard"
)

var AllRole = []Role{
	RoleExecutiveBoard,
	RoleAtLargeBoard,
}

func (e Role) IsValid() bool {
	switch e {
	case RoleExecutiveBoard, RoleAtLargeBoard:
		return true
	}
	return false
}

func (e Role) String() string {
	return string(e)
}

func (e *Role) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Role(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Role", str)
	}
	return nil
}

func (e Role) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
