interface _RbsRailsPathHelpers
  def rails_info_properties_path: (*untyped) -> String
  def rails_info_routes_path: (*untyped) -> String
  def rails_info_path: (*untyped) -> String
  def rails_mailers_path: (*untyped) -> String
  def stylesheets_club_path: (*untyped) -> String
  def players_path: (*untyped) -> String
  def new_player_path: (*untyped) -> String
  def edit_player_path: (*untyped) -> String
  def player_path: (*untyped) -> String
  def mot_ms_path: (*untyped) -> String
  def sync_matches_path: (*untyped) -> String
  def match_mot_ms_path: (*untyped) -> String
  def new_match_mot_m_path: (*untyped) -> String
  def edit_match_mot_m_path: (*untyped) -> String
  def match_mot_m_path: (*untyped) -> String
  def match_rev_guesses_path: (*untyped) -> String
  def new_match_rev_guess_path: (*untyped) -> String
  def edit_match_rev_guess_path: (*untyped) -> String
  def match_rev_guess_path: (*untyped) -> String
  def match_pick_em_vote_path: (*untyped) -> String
  def matches_path: (*untyped) -> String
  def new_match_path: (*untyped) -> String
  def edit_match_path: (*untyped) -> String
  def match_path: (*untyped) -> String
  def clubs_path: (*untyped) -> String
  def new_club_path: (*untyped) -> String
  def edit_club_path: (*untyped) -> String
  def club_path: (*untyped) -> String
  def memberships_webhooks_path: (*untyped) -> String
  def new_user_session_path: (*untyped) -> String
  def user_session_path: (*untyped) -> String
  def destroy_user_session_path: (*untyped) -> String
  def new_user_password_path: (*untyped) -> String
  def edit_user_password_path: (*untyped) -> String
  def user_password_path: (*untyped) -> String
  def cancel_user_registration_path: (*untyped) -> String
  def new_user_registration_path: (*untyped) -> String
  def edit_user_registration_path: (*untyped) -> String
  def user_registration_path: (*untyped) -> String
  def import_users_path: (*untyped) -> String
  def user_memberships_path: (*untyped) -> String
  def new_user_membership_path: (*untyped) -> String
  def user_membership_path: (*untyped) -> String
  def accept_invitation_for_user_membership_relative_path: (*untyped) -> String
  def user_membership_relatives_path: (*untyped) -> String
  def new_user_membership_relative_path: (*untyped) -> String
  def user_membership_relative_path: (*untyped) -> String
  def users_path: (*untyped) -> String
  def new_user_path: (*untyped) -> String
  def edit_user_path: (*untyped) -> String
  def user_path: (*untyped) -> String
  def download_path: (*untyped) -> String
  def cancel_user_membership_path: (*untyped) -> String
  def user_home_path: (*untyped) -> String
  def standings_path: (*untyped) -> String
  def transactions_path: (*untyped) -> String
  def faq_path: (*untyped) -> String
  def contact_path: (*untyped) -> String
  def nominate_path: (*untyped) -> String
  def root_path: (*untyped) -> String
  def rails_info_properties_url: (*untyped) -> String
  def rails_info_routes_url: (*untyped) -> String
  def rails_info_url: (*untyped) -> String
  def rails_mailers_url: (*untyped) -> String
  def stylesheets_club_url: (*untyped) -> String
  def players_url: (*untyped) -> String
  def new_player_url: (*untyped) -> String
  def edit_player_url: (*untyped) -> String
  def player_url: (*untyped) -> String
  def mot_ms_url: (*untyped) -> String
  def sync_matches_url: (*untyped) -> String
  def match_mot_ms_url: (*untyped) -> String
  def new_match_mot_m_url: (*untyped) -> String
  def edit_match_mot_m_url: (*untyped) -> String
  def match_mot_m_url: (*untyped) -> String
  def match_rev_guesses_url: (*untyped) -> String
  def new_match_rev_guess_url: (*untyped) -> String
  def edit_match_rev_guess_url: (*untyped) -> String
  def match_rev_guess_url: (*untyped) -> String
  def match_pick_em_vote_url: (*untyped) -> String
  def matches_url: (*untyped) -> String
  def new_match_url: (*untyped) -> String
  def edit_match_url: (*untyped) -> String
  def match_url: (*untyped) -> String
  def clubs_url: (*untyped) -> String
  def new_club_url: (*untyped) -> String
  def edit_club_url: (*untyped) -> String
  def club_url: (*untyped) -> String
  def memberships_webhooks_url: (*untyped) -> String
  def new_user_session_url: (*untyped) -> String
  def user_session_url: (*untyped) -> String
  def destroy_user_session_url: (*untyped) -> String
  def new_user_password_url: (*untyped) -> String
  def edit_user_password_url: (*untyped) -> String
  def user_password_url: (*untyped) -> String
  def cancel_user_registration_url: (*untyped) -> String
  def new_user_registration_url: (*untyped) -> String
  def edit_user_registration_url: (*untyped) -> String
  def user_registration_url: (*untyped) -> String
  def import_users_url: (*untyped) -> String
  def user_memberships_url: (*untyped) -> String
  def new_user_membership_url: (*untyped) -> String
  def user_membership_url: (*untyped) -> String
  def accept_invitation_for_user_membership_relative_url: (*untyped) -> String
  def user_membership_relatives_url: (*untyped) -> String
  def new_user_membership_relative_url: (*untyped) -> String
  def user_membership_relative_url: (*untyped) -> String
  def users_url: (*untyped) -> String
  def new_user_url: (*untyped) -> String
  def edit_user_url: (*untyped) -> String
  def user_url: (*untyped) -> String
  def download_url: (*untyped) -> String
  def cancel_user_membership_url: (*untyped) -> String
  def user_home_url: (*untyped) -> String
  def standings_url: (*untyped) -> String
  def transactions_url: (*untyped) -> String
  def faq_url: (*untyped) -> String
  def contact_url: (*untyped) -> String
  def nominate_url: (*untyped) -> String
  def root_url: (*untyped) -> String
end
