version: 2.0
jobs:
  test-java:
    docker:
      - image: gradle:7.2.0-jdk11
    resource_class: small
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - gradle-repo-check-v1-{{ .Branch }}-{{ checksum "api/gradle.lockfile" }}
            - gradle-repo-check-v1-{{ .Branch }}-
            - gradle-repo-check-v1-
      - run:
          name: Lint
          working_directory: ./api
          command: gradle detekt
      - run:
          name: Test
          working_directory: ./api
          command: gradle test
      - store_test_results:
          path: ./api/build/test-results/test
      - save_cache:
          paths:
            - ./api/.gradle
          key: gradle-repo-check-v1-{{ .Branch }}-{{ checksum "api/gradle.lockfile" }}
      - persist_to_workspace:
          root: ./api
          paths: 
            - testReport.xml

  # TODO
  # test-typescript:
  #   docker: []
  #   steps: []

  notify-coverage-start:
    docker:
        - image: cimg/base:2021.10-20.04
    resource_class: small
    steps:
      - checkout
      - run:
          name: Download CC Test Reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./coverage/cc-test-reporter
            chmod +x ./coverage/cc-test-reporter
      - run:
          name: Inform CircleCI
          command: ./coverage/cc-test-reporter before-build
      - persist_to_workspace:
          root: .
          paths: 
            - '*'
  
  report-coverage:
    docker:
      - image: cimg/base:2021.10-20.04
    resource_class: small
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Format Java Report
          working_directory: ./coverage
          command: |
            pwd
            ls -a .
            ./cc-test-reporter format-coverage ../testReport.xml -t jacoco -o "codeclimate.$CIRCLE_NODE_INDEX.json"
      - run:
          name: Report Coverage
          command: ./coverage/cc-test-reporter sum-coverage --output - codeclimate.*.json | ./cc-test-reporter --debug --input -

workflows:
  version: 2

  commit:
    jobs:
      - notify-coverage-start
      - test-java:
          requires:
            - notify-coverage-start
      - report-coverage:
          requires:
            - test-java

