FROM golang:1.19.2
LABEL maintainer="Midnight Riders <info@midnightriders.com>"

WORKDIR /go

RUN go install github.com/cosmtrek/air@latest
RUN echo "$PATH"
WORKDIR /usr/local/bin
SHELL [ "/bin/bash", "-o", "pipefail", "-c" ]
RUN curl -L https://github.com/golang-migrate/migrate/releases/download/v4.13.0/migrate.linux-amd64.tar.gz | tar xvz \
    && mv migrate.linux-amd64 migrate

WORKDIR /go/src/github.com/MidnightRiders/MemberPortal/server
COPY go.mod go.sum ./
RUN go mod download

CMD [ "air" ]
