#!/usr/bin/env bash

set -eo pipefail

cd "$(dirname "$0")/.."

script/update

shutdown() {
  ec="$?"

  docker-compose down
  [ -f tmp/pids/server.pid ] && rm -f tmp/pids/server.pid

  exit "$ec"
}

trap shutdown INT

docker compose up
