#!/bin/bash -e

gradleRun() {
  if [ "$DEBUG" = "true" ]; then
    JAVA_OPTS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005" gradle run -t
  else
    gradle run -t
  fi
}

gradle jar

gradleRun &
  gradle jar -t
